const messages = {
    en: {
      emailExists: "Email already exists",
      userCreated: "User registered successfully",
      internalServerError: "Internal Server Error",
      invalidCredentials: "Invalid email or password",
      loginSuccess: "Login successful",

      errorFetchingBooks: "Error fetching books",
      bookNotFound: "Book not found",
      errorFetchingBook: "Error fetching book",
      errorCreatingBook: "Error creating book",
      errorUpdatingBook: "Error updating book",
      bookCreatedSuccessfully: "Library created successfully",
      bookUpdatedSuccessfully: "Book updated successfully",
      bookDeletedSuccessfully: "Book deleted successfully",
      errorDeletingBook: "Error deleting book",

      errorFetchingLibraries: "Error fetching libraries",
      librariesFetchedSuccessfully: "Libraries fetched successfully",
      libraryNotFound: "Library not found",
      errorFetchingLibrary: "Error fetching library",
      libraryFetchedSuccessfully: "Library fetched successfully",
      errorCreatingLibrary: "Error creating library",
      libraryCreatedSuccessfully: "Library created successfully",
      errorUpdatingLibrary: "Error updating library",
      libraryUpdatedSuccessfully: "Library updated successfully",
      errorDeletingLibrary: "Error deleting library",
      libraryDeletedSuccessfully: "Library deleted successfully",
      
      libraryNotFound: "Library not found",
      bookNotFound: "Book not found",
      inventoryFetchedSuccessfully: "Library inventory fetched successfully",
      errorFetchingInventory: "Error fetching library inventory",
      bookAddedToInventory: "Book added to library inventory successfully",
      errorAddingBookToInventory: "Error adding book to library inventory",
      bookRemovedFromInventory: "Book removed from library inventory successfully",
      bookNotInInventory: "Book not found in library inventory",
      errorRemovingBookFromInventory: "Error removing book from library inventory",

      bookNotFound: "Book not found",
      bookAlreadyBorrowed: "Book is already borrowed",
      bookBorrowedSuccessfully: "Book borrowed successfully",
      bookNotBorrowedByUser: "Book not borrowed by this user",
      bookReturnedSuccessfully: "Book returned successfully",
      errorProcessingRequest: "Error processing request",

    },

    hi: {
      emailExists: "ईमेल पहले से मौजूद है",
      userCreated: "उपयोगकर्ता सफलतापूर्वक पंजीकृत हुआ",
      internalServerError: "आंतरिक सर्वर त्रुटि",
      invalidCredentials: "अमान्य ईमेल या पासवर्ड",
      loginSuccess: "लॉगिन सफल",

      errorFetchingBooks: "पुस्तकें प्राप्त करने में त्रुटि",
      bookNotFound: "पुस्तक नहीं मिली",
      errorFetchingBook: "पुस्तक प्राप्त करने में त्रुटि",
      errorCreatingBook: "पुस्तक बनाने में त्रुटि",
      errorUpdatingBook: "पुस्तक अपडेट करने में त्रुटि",
      bookCreatedSuccessfully: "पुस्तक सफलतापूर्वक बनाया गया",
      bookUpdatedSuccessfully: "पुस्तक सफलतापूर्वक अपडेट हुई",
      bookDeletedSuccessfully: "पुस्तक सफलतापूर्वक हटाई गई",
      errorDeletingBook: "पुस्तक हटाने में त्रुटि",

      errorFetchingLibraries: "पुस्तकालय प्राप्त करने में त्रुटि",
      librariesFetchedSuccessfully: "पुस्तकालय सफलतापूर्वक प्राप्त किए गए",
      libraryNotFound: "पुस्तकालय नहीं मिला",
      errorFetchingLibrary: "पुस्तकालय प्राप्त करने में त्रुटि",
      libraryFetchedSuccessfully: "पुस्तकालय सफलतापूर्वक प्राप्त किया गया",
      errorCreatingLibrary: "पुस्तकालय बनाने में त्रुटि",
      libraryCreatedSuccessfully: "पुस्तकालय सफलतापूर्वक बनाया गया",
      errorUpdatingLibrary: "पुस्तकालय अपडेट करने में त्रुटि",
      libraryUpdatedSuccessfully: "पुस्तकालय सफलतापूर्वक अपडेट किया गया",
      errorDeletingLibrary: "पुस्तकालय हटाने में त्रुटि",
      libraryDeletedSuccessfully: "पुस्तकालय सफलतापूर्वक हटाया गया",

      libraryNotFound: "पुस्तकालय नहीं मिला",
      bookNotFound: "पुस्तक नहीं मिली",
      inventoryFetchedSuccessfully: "पुस्तकालय सूची सफलतापूर्वक प्राप्त की गई",
      errorFetchingInventory: "पुस्तकालय सूची प्राप्त करने में त्रुटि",
      bookAddedToInventory: "पुस्तक को पुस्तकालय सूची में सफलतापूर्वक जोड़ा गया",
      errorAddingBookToInventory: "पुस्तक को पुस्तकालय सूची में जोड़ने में त्रुटि",
      bookRemovedFromInventory: "पुस्तक को पुस्तकालय सूची से सफलतापूर्वक हटाया गया",
      bookNotInInventory: "पुस्तक पुस्तकालय सूची में नहीं मिली",
      errorRemovingBookFromInventory: "पुस्तक को पुस्तकालय सूची से हटाने में त्रुटि",

      bookNotFound: "पुस्तक नहीं मिली",
      bookAlreadyBorrowed: "पुस्तक पहले से ही उधार ली गई है",
      bookBorrowedSuccessfully: "पुस्तक सफलतापूर्वक उधार ली गई",
      bookNotBorrowedByUser: "यह पुस्तक इस उपयोगकर्ता द्वारा उधार नहीं ली गई है",
      bookReturnedSuccessfully: "पुस्तक सफलतापूर्वक लौटाई गई",
      errorProcessingRequest: "अनुरोध संसाधित करने में त्रुटि",

    },
  };
  
  module.exports = messages;